on:
  pull_request:
    types: [ closed ]
    
jobs:
  job-delta:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          /repos/${{ github.repository }}/commits/${{ github.head_ref }}/check-suites |
          jq '.check_suites[] | .id'
