on:
  pull_request:
    types: [ closed ]
    
jobs:
  job-delta:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.sha }}"
      
          curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/check-runs
