on:
  pull_request:
    types: [ closed ]
    
jobs:
  job-delta:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/check-runs
        env:
          GH_TOKEN: ${{ github.token }}
